[package]
name = "cce-fx"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
cce-ui = { git = "https://github.com/lsgalante/cce-ui.git", rev = "eeca5b715926707fcf3365f929f9b497bf3bba7d" }
cce-window-manager = { git = "https://github.com/lsgalante/cce-window-manager.git", rev = "416f42c78fb63131121d8f2a86a607c31c829fc5" }
xkbcommon = "0.7"
serde = { version = "1", features = ["derive"] }
nix = { version = "0.29", features = ["signal", "process", "fs", "poll", "resource"] }
libc = "0.2"
bitflags = "2"
tokio = { version = "1.35", features = ["full"] }
serde_json = "1.0"
kdl = "4.6"
png = "0.17"
fontdue = "0.9.3"
clap = { version = "4.4", features = ["derive"] }
log = "0.4"
env_logger = "0.11"

[build-dependencies]
bindgen = "0.69"
pkg-config = "0.3"
cc = "1.0"

[[bin]]
name = "cce-fx"
path = "src/bin/cce.rs"

[profile.release]
debug = true


